apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ubqi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jhutar-tenant/my-app/devfile-sample-ubqi@sha256:2f8a28cd8fcc5d17a85a4780317f3dd4e84d3cef3393f01c19edfc05eaaaf85e
        name: my-nodejs
        resources: {}
status: {}
